
= Accumulator

Suppose you have a list of data values, and you need to know how many
of those data values are less than zero.

== example

[source, python]
----
data = [37.5, -0.01, 99.34, 14.7, ...]
counter = 0
for item in data:
   if item < 0:
      counter = counter + 1
print("Number a values < 0: ", counter)
----

== explanation/notes

The `counter` variable is an example of an *accumulator*.
It starts at zero, and we check each data value in the list. Each time
we find one that meets a certain condition (here, less than zero), we
increment the counter variable. At the end of the `for` loop we have
built-up/accumulated the answer (how many values are less than zero).

This *accumulator* pattern (initialize to zero, build up solution one
item at a time) arises in different situations, and can be 
reused to solve problems in these different areas.

Here are some examples:

- keep track of consecutive correct answers, print a message if user gets
  5-in-a-row correct ("Good work!")
- get data from file, keep a count of how many invalid data items read in
- get numbers from user, keep a running sum of the input numbers 

== another example

Here's the "keep a running sum" example mentioned above.
In this example we are getting numbers from the user, then
calculating and displaying the average of those numbers.

[source, python]
----
ngrades = int(input("Number of grades: "))

total = 0
for n in range(ngrades):
    grade = float(input("grade: "))
    total = total + grade

avegr = total/ngrades
print("Average grade: ", avegr)
----

== string accumulator

You can also build-up/accumulate strings, starting with an empty string.
What do you think this `for` loop will print to the screen?

[source, python]
----
output = ""
for i in range(10):
   output += "*"
   print(output)
----

Note: the `+=` operator is shorthand for *assignment addition*.
So the `output += "*"` line above is equivalent to this:

    output = output + "*"

