
= `assert()`

The `assert()` function is a simple way to add semi-automatic testing to your
programs and libraries. An `assert()` statement gives no output if the test
succeeds, but gives an `AssertionError` if the test fails. 

== example

    >>> assert(1==1)
    >>> assert(1+1==2)
    >>> assert(1+1!=3)
    >>> assert(1+1==3)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AssertionError
    >>> assert("hello".upper()=="HELLO")
    >>> from math import sqrt
    >>> assert(sqrt(4)==2)

== explanation/notes

In the above examples, only the fourth test fails (`1+1==3`)
and crashes with an `AssertionError`. If tests that pass produce
no output, you can add these statements to a test function in your code
and periodically run the test function to make sure everything is
still working (no news is good news).

== another example

Suppose I wrote a `binarySearch(x,L)` function that looks for `x` in the
list `L`, using a binary search. Here's an example of a function I
might add, to test all possible cases I can think of:

[source,python]
----
def testcode():
    """test the binarySearch function"""
    x = 5
    L = [1,2,3,4,5,6,7,8,9,10]
    letters = list("BCDEFGHIKLMNPQRSTWXY")
    assert(binarySearch(x,L)==True)
    assert(binarySearch(-20,L)==False)
    assert(binarySearch("F",letters)==True)
    assert(binarySearch("Z",letters)==False)
    assert(binarySearch("A",letters)==False)
    assert(binarySearch("A",["A"])==True)
    assert(binarySearch("A",[])==False)
    for item in L:
        assert(binarySearch(item,L)==True)
    for item in L:
        assert(binarySearch(item,letters)==False)
    print("All tests passed!")
----

If I run the `testcode()` function and see the "All tests passed!"
message at the bottom, I feel confident that my search function is
working. And if I ever make changes to my search function, I can just
run the test code again to make sure I didn't break anything.
