
= Files


== example

    $ cat poem.txt
    Roses are red.
    Violets are blue.
    Sugar is sweet.
    And so are you!
    $ python3
    >>> infile = open("poem.txt", "r")
    >>> lines = infile.readlines()
    >>> print(lines)
    ['Roses are red.\n', 'Violets are blue.\n', 'Sugar is sweet.\n', 'And so are you!\n']

== explanation/notes

The variable `infile` stores the *file object* returned by
the `open()` function. We have opened the file named "poem.txt"
for *reading* (using the "r" argument). The `readlines()` method
reads in all lines from the file and returns them as a list
of strings. We assign this list of strings to the `lines` variable.
Note how each line from the file ends with a *newline character*
(the '\n').

For file objects, here are the frequently-used methods:

.File Object Methods
[options="header"]
|=======================
|method |description                 |example              |returns
|`readlines()`|reads all lines from file|`infile.readlines()`|list of strings
|`readline()`|reads one line from file|`infile.readline()`|string
|`close()`|closes the file|`infile.close()`|nothing
|`write()`|writes one line to file|`outfile.write('hi!\n')`|number of chars written
|=======================

== another example

Files are another example of a *sequence* in python (like strings and
lists). We can use sequences in `for` loops, so we could also read in
all lines from a file like this:

[source,python]
----
inf = open("poem.txt", "r")
lines = []
for line in inf:
   lines.append(line)
inf.close()
----

This does exactly the same thing as the previous example. It's just
shown here as an example of iterating over each line in the file.
Sometimes you want to process the data line-by-line, as you read each
line in (instead of reading them all in at once with `readlines()`).

=== writing to files

Similar to reading, but the file is opened with the "w" flag:

    >>> outfile = open("newfile", "w")
    >>> outfile.write("We love CompSci!!\n")
    >>> outfile.write("Here's another line...\n")
    >>> outfile.close()
    >>>
    $ cat newfile
    We love CompSci!!
    Here's another line...
    $

Note how we have to include the newline character ('\n') at the end of
each string we write. Otherwise the file would contain just one long
line. Also, if the file already exists, and we open it for writing, any
data already in the file is wiped out and replaced by whatever we write.

---

See also:

- <<_strings>>
- <<_lists>>
- <<_objects_and_methods>>
