
= `for` loops

== example

    >>> names = ["Andy", "Kevin", "Lauri", "Jeff"]
    >>> for name in names:
    ...    print("Hello, ", name, "!")
    ... 
    Hello,  Andy !
    Hello,  Kevin !
    Hello,  Lauri !
    Hello,  Jeff !

Note: I don't type the dot dot dots (...). That's just the python
shell telling me it expects something more -- the indented code block
of the `for` loop. On the last line, before the "Hello..." output, I 
just hit the Enter key (no indentation).

    >>> limit = 10
    >>> for i in range(limit):
    ...     output = 2*i
    ...     print(i,":",output)
    ...
    0 : 0
    1 : 2
    2 : 4
    3 : 6
    4 : 8
    5 : 10
    6 : 12
    7 : 14
    8 : 16
    9 : 18


== explanation/notes

`for` loops are great when we want to repeat something, and we know how many
times we want to repeat. In the first example above, we want to print a greeting
for *however many names are in our list of names*. In the second example, we want
to create and print something *limit* times.

The `for` loop syntax is:

    for <variable> in <sequence>:
       indented code
       indented code
       indented code

The variable is any name you want (but choose good variable names,
unlike this next example!):

    >>> for n in names:
    ...    print("Hello, ", n, "!")
    ...
    Hello,  Andy !
    Hello,  Kevin !
    Hello,  Lauri !
    Hello,  Jeff !

And the variable *takes on all values in the sequence*, one at a time.
Each time the variable gets a new value from the sequence, the indented 
code lines (i.e., the code *block*) are executed.

There must be one (or more) indented code lines in the `for` loop.
The next *unindented* line *ends* the code block! So if I had this:

[source,python]
----
limit = 10
for i in range(limit):
    output = 2*i
    print(i,":",output)
print("-"*20)
----

It would print this (see how the dashed line is after or *outside* the `for` loop!):

    0 : 0
    1 : 2
    2 : 4
    3 : 6
    4 : 8
    5 : 10
    6 : 12
    7 : 14
    8 : 16
    9 : 18
    --------------------

The *sequence* in a for loop can be many things: a list, a string, or even a file.
If the sequence is:

- a list, the variable becomes each item in the list
- a string, the variable becomes each character in the string
- a file, the variable becomes each line in the file

Here's a string sequence example:

    >>> for ch in "ABCDEFG":
    ...    print(ch*3)
    ...
    AAA
    BBB
    CCC
    DDD
    EEE
    FFF
    GGG

These examples may all seem trivial or a little silly, but `for` loops are very important!
As we learn more python, we'll see some more useful examples.

=== the `range()` function

The `range()` function is a built-in python function that is super-useful
for creating sequences used in `for` loops. Technically (in python 3) it 
is it's own type, but you can see what it's doing if you call the `list()`
function on it:

    >>> x = range(10)
    >>> type(x)
    <class 'range'>
    >>> list(x)
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Given a single integer (say, `n`) it creates a range of integers from 0 to `n-1`.

The full syntax is `range(start, stop, step)`, but you can leave out the start
(defaults to 0) and/or the step (defaults to 1). Here's an example using all of them:

    >>> list(range(1,11,2))
    [1, 3, 5, 7, 9]
    >>> list(range(10,-1,-1))
    [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


== another example

    >>> n = 7
    >>> for i in range(1,11):
    ...    answer = i*n
    ...    print(n,"x",i,"=",answer)
    ... 
    7 x 1 = 7
    7 x 2 = 14
    7 x 3 = 21
    7 x 4 = 28
    7 x 5 = 35
    7 x 6 = 42
    7 x 7 = 49
    7 x 8 = 56
    7 x 9 = 63
    7 x 10 = 70

---

See also: 

- <<_functions_builtin>>
