
= Functions: builtin

== example

    >>> S = "Swarthmore"
    >>> print(S)
    Swarthmore
    >>> print(len(S))
    10
    >>> L = list(S)
    >>> print(L)
    ['S', 'w', 'a', 'r', 't', 'h', 'm', 'o', 'r', 'e']
    >>> x = int(5.371)
    >>> print(x)
    5
    >>> type(x)
    <class 'int'>

== explanation/notes

A function is just a block of code with a given name. You use the name
followed by parentheses to *call* the function: `print("hello")`. Calling
the function executes the code block. After the function executes, the program
that called the function continues running.

Using functions, either built-in or creating your own, is the primary way
to manage code complexity. As you start to write larger programs, you will 
break large tasks into smaller, manageable functions.

In all of the function calls above, an *argument* is provided inside the parentheses.
In `print("hello")`, the `print()` function is *called* with the string argument `"hello"`.
The arguments are just data sent *to* the function. Functions can have zero or more
arguments. Here's a call to `print()` with 3 arguments:

    >>> name = "Jeff"
    >>> print("Hello, ", name, "!")
    Hello,  Jeff !

Sometimes, but not always, a function returns something to the program that
called the function. In `x = int(5.371)` the float 5.371 is sent to the `int()`
function, which converts (truncates) it into an integer (5), and *returns* the result 
(the 5).  This result is then immediately assigned to the variable `x`.

Here are some useful built-in python functions:

.Useful Python Built-In Functions
[options="header"]
|=======================
|function |description                 |example              |returns
|`print()`|prints arguments to terminal|`print("hello")`     |nothing
|`int()`  |converts arg to integer     |`result = int(3.141)`|integer
|`float()`|converts arg to float       |`result = float("5")`|float
|`str()`  |converts arg to string      |`result = str(10)`   |string
|`type()` |displays data type of arg   |`type(10)`           |type object
|`len()`  |returns length or sequence  |`len(S)`             |integer
|`input()`|gets input from the user    |`answer=input("name: ")`|string
|=======================

== another example

The `input()` function is used to get input from the user.
It will pause the program, waiting for the user to type something
and hit *Enter*. The argument provided becomes the *prompt* to the
user.

    >>> age = input("How old are you? ")
    How old are you? 53        <-- user types 53 here and hits Enter key
    >>> print(age)
    53
    >>> type(age)
    <class 'str'>

Note the `input()` function **always returns a string**, no matter what
the user enters (characters, digits, etc).

If you know the user is going to enter a valid integer, you can use
the `int()` function to convert the input string to an integer:

    >>> age = int(input("How old are you? "))
    How old are you? 53         
    >>> print(age)
    53
    >>> type(age)
    <class 'int'>

But this won't work if the user enters something that can't be converted
to an integer:

    >>> age = int(input("How old are you? "))
    How old are you? pony
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ValueError: invalid literal for int() with base 10: 'pony'

See later sections 
(<<_while_indefinite_loops>>, <<_tryexcept>>)
for ways to handle invalid input.
