
= `import` statements

Python libraries contain commonly-used functions. In order to use the
functions, we need to first import the correct library.

== example

Here's an example of importing the python `math` library, to gain 
access to the `sqrt()` function:

[source,python]
----
from math import *

for i in range(1,6):
    result = sqrt(i)
    print("Sqrt(%d) = %.2f" % (i, result))
----

Running the above code would produce this output:

    Sqrt(1) = 1.00
    Sqrt(2) = 1.41
    Sqrt(3) = 1.73
    Sqrt(4) = 2.00
    Sqrt(5) = 2.24

== explanation/notes

In python there are two common ways to import libraries:

    from math import *              import math
    result = sqrt(5)                result = math.sqrt(5)

The example on the left is typically used in our intro courses, as
it requires less typing and makes short codes easier to read.

For larger, more complex codes, the example on the right is preferred.
Calling the function as `math.sqrt()` avoids any possibility of two
functions from different libraries having the same name (i.e., if they
*did* have the same name, calling them as `library.function()` would
allow us to know which library each was from).

Some useful python libraries include:

.Python Libraries
[options="header"]
|=======================
|library |description                 |functions
|`math`|basic mathematical functions|`sqrt()`, `sin()`, `cos()`, `radians()`, `log2()`
|`random`|random number functions|`randrange()`, `choice()`, `random()`
|`time`|manipulate time values|`sleep()`, `time()`
|=======================

To see documentation on any library, simply import the library and 
then call the `help()` function:

    >>> import math
    >>> help(math)

Use 'q' to quit the help documentation.

Usually *all* import statements are at the top of the file, before any
code or function definitions:

[source,python]
----
"""
Comments...
"""

from math import *
from random import *

def main():
    main code here...
    main code here...
    main code here...

main()
----


== another example

    >>> from random import *
    >>> L = list("ABCDEFG")
    >>> choice(L)
    'E'
    >>> choice(L)
    'A'
    >>> choice(L)
    'F'

You can also just import *one* function if you know that's all you need:

    >>> from math import sqrt
    >>> result = sqrt(5)

---

See also:

- <<_functions_builtin>>
- <<_random_library>>
