
= Lists


== example

    >>> names = ["Kevin", "Andy", "Lauri", "Jeff"]
    >>> for name in names:
    ...    print("Hello, %s!" % (name))
    ...
    Hello, Kevin!
    Hello, Andy!
    Hello, Lauri!
    Hello, Jeff!

== explanation/notes

A **list is a sequence** of items, where
each item could be anything (an integer, a float, a string, etc),
even another list!

Like strings, lists have a length: the number of items
in the list.

    >>> L = ["pony","donkey","zebra"]
    >>> print(len(L))
    3

Each item in a list has a position, also called an *index*. 
In python, positions start at 0, so the string "pony" in the
above list is at position 0, and "zebra" is at position 2.

You can access individual items in a list using
*square-bracket indexing*:

    >>> print(L[2])
    zebra
    >>> print(L[1])
    donkey

Any *sequence* in python can be used in a `for` loop. 
For lists, we can either loop over items in the list (see `names` list
above) *or* indices.  Here is an example using `range()` to loop over indicies:

    >>> L = ["pony","donkey","zebra"]
    >>> for i in range(len(L)):
    ...   print(i,L[i])
    ...
    0 pony
    1 donkey
    2 zebra


Unlike strings, **lists are *mutable* **.
This means their contents *can* be modified,
without having to create a new list.

    >>> L = ["pony","donkey","zebra"]
    >>> L[2] = "horse"       # assign to position 2 in the list
    >>> print(L)
    ["pony","donkey","horse"]

The `in` (membership) operator also works for lists:

    >>> positives = ["y","Y","yes","Yes","YES"]
    >>> "no" in positives
    False
    >>> "yes" in positives
    True

### common list methods

Lists are *objects* in Python, and thus have *methods* that
we can invoke on them.  Here are a few that may be particularly useful
(run `help(list)` in the python interpreter to see the full set):

.Useful Python list Methods
[options="header"]
|=======================
|list method |result
| append(item)   | add item to end of list 
| insert(index,item)   | insert item at index 
| extend(L1)      | add list L1 to original list 
| sort()          | sort the list 
| reverse()       | reverse the list 
| count(item)     | return number of occurrences of item in list 
| index(item)      | return index of first occurrence of item 
| pop(index)      | remove and return item at index 
|=======================

    >>> L = list("ABCDEFG")
    >>> print(L)
    ['A', 'B', 'C', 'D', 'E', 'F', 'G']
    >>> L.append("X")
    >>> print(L)
    ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'X']
    >>> L.extend(["Y","Z"])
    >>> print(L)
    ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'X', 'Y', 'Z']
    >>> L.reverse()
    >>> print(L)
    ['Z', 'Y', 'X', 'G', 'F', 'E', 'D', 'C', 'B', 'A']
    >>> L.sort()
    >>> print(L)
    ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'X', 'Y', 'Z']
    >>> L.count("E")
    1
    >>> L.index("E")
    4
    >>> L.pop(4)
    'E'
    >>> print(L)
    ['A', 'B', 'C', 'D', 'F', 'G', 'X', 'Y', 'Z']
    >>> L.insert(1,"hello")
    >>> print(L)
    ['A', 'hello', 'B', 'C', 'D', 'F', 'G', 'X', 'Y', 'Z']


include::converting.adoc[]


== another example

Here's a list-of-lists example:

    >>> LOL = [["jeff", 77], ["lila", 99.0], ["joshua", 87.3]]
    >>> for item in LOL:
    ...    print("%s's final grade is %.1f" % (item[0], item[1]))
    ...
    jeff's final grade is 77.0
    lila's final grade is 99.0
    joshua's final grade is 87.3

---

See also:

- <<_objects_and_methods>>
- <<_strings>>

