

= `def main()`

== example

[source, python]
----
def main():
   name = input("What is your name? ")
   print("Hello, %s!" % (name))

main()
----

== explanation/notes

Above we define a short function called *main*, and then
call the function on the very last line. Remember, for functions,
anything indented is part of the function, so the first *unindented*
line (in this case, the call to `main()`) marks the end of the function
definition above.

Most programs have a *main* function that drives the whole program.
Reading through `main()` should give the reader a good overview of what
the whole program does (like an outline). And just like other functions,
if `main()` is more than one screen, it's probably too long (and should
be broken up into more functions).

A common practice is to put `def main()` as the *first* function defined
in the file, with others below. This makes it easy to see/find when you
open the program for editing.

== another example

[source, python]
----
def main():
   printRules()
   score = 0
   GAMEOVER = False
   while not GAMEOVER:
      displayBoard(score)
      score = Turn(score)
      if score < 0: 
         GAMEOVER = True
   print("Thanks for playing!!")
----

As you can probably guess, the above is a `main()` function from a simple
game. Another function (`printRules()`) is called to display the rules of
the game, then the board is displayed and the user takes
a turn. This repeats (display, turn, display, turn, ...) until the game is over.

---

See also:

- <<_functions_simple>>
