
= `while` (indefinite) loops


== example

Sometimes you want to repeat a code block, but you don't know exactly how many
times to repeat.  For example, in a game like tic-tac-toe, you might want to
get the player's move, then update board, then get the next player's move, and
so on, until the game is over. The "get move, update board" code might be
executed 5 or more times. This is called an *indefinite* loop.

Here's an example using random numbers, so we don't know how many times the
code block will run, and each time we run this code the output will be
different (because the random numbers chosen will be different):

[source,python]
----
from random import *

value = 0
limit = 10
while value < limit:
   print("value: %2d -- limit = %2d" % (value, limit))
   print("picking random number from 1-10...")
   randnumber = randrange(1,11)
   print(">>>>> picked %d" % randnumber)
   if randnumber > 6:
      value = value + 2
print("-"*30)
print("Done!")
----

Here's one example of running the above code:

    value:  0 -- limit = 10
    picking random number from 1-10...
    >>>>> picked 7
    value:  3 -- limit = 10
    picking random number from 1-10...
    >>>>> picked 8
    value:  6 -- limit = 10
    picking random number from 1-10...
    >>>>> picked 4
    value:  6 -- limit = 10
    picking random number from 1-10...
    >>>>> picked 10
    value:  9 -- limit = 10
    picking random number from 1-10...
    >>>>> picked 8
    ------------------------------
    Done!

== explanation/notes

The above `while` loop keeps picking random numbers as long as (while)
`value` is less than `limit`. Note that in the code block (the indented
code below the `while value < limit` line), it is possible that
`value` will be changed (increased by 2), *if* the random number chosen
is greater than 6. 

The `while` loop syntax is:

    while <boolean expression>:
       do this line
       and this indented line
       and this indented line

This looks just like the `if` statement, and it is, except that after the code block is
run, we *go back to the top and re-check the boolean expression*. If the boolean expression
is still `True`, we run the code block *again*. As long as (while) the boolean expression
evaluates to `True`, we'll keep running the code block. After each run of the code block,
we re-check the boolean expression to see if it is `True` or `False`. Once it's `False`, we
skip the code block and continue on with the rest of the program.

Don't confuse the `if` statement with the `while` loop!

    if x < 20:                     while x < 20:
       do this line                   do this line

Both of those will execute the "do this line" if `x` is less than 20.
The `while` loop will then go back and re-check if `x` is still less than
20, where the `if` code will continue on with the rest of the program.

What do you think this code will do?

[source,python]
----
x = 0
while x < 100:
   print(x)
   print("--------------------")
----

This is an *infinite* loop, that will just print 0 and a dashed line over and
over and over. **You can use `Ctrl-c` to kill a program stuck in an infinite loop**.


== another example

Have you ever used Duolingo, where the owl cheers you on, and notices when
you give the correct answer three times in a row?

[source,python]
----
from random import *

factor = 9
inarow = 0
while inarow < 3:
   otherfactor = randrange(2,13)        # pick number 2-12
   answer = factor * otherfactor        # calculate the right answer
   question = "What is %d*%d? " % (factor,otherfactor)
   useranswer = int(input(question))    # get user's answer
   if useranswer == answer:
     inarow = inarow + 1
   else:
     print("Nope...answer = %d" % answer)
     inarow = 0
print("Three in a row...good work!")
----

And here's one possible run of the above code:

    What is 9*7? 63
    What is 9*10? 90
    What is 9*2? 19
    Nope...answer = 18
    What is 9*12? 108
    What is 9*5? 45
    What is 9*8? 72
    Three in a row...good work!

---

See also: 

- <<_random_library>>
- <<_ifelse_branching>>
- <<_accumulator>>
